version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: diploma_backend
    restart: always
    env_file:
      - .env
    expose:
      - "8000"

  frontend:
    build: ./Frontend
    container_name: diploma_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
